### PR TITLE
Better routing using RouteGroups and path prefixes

### PR DESCRIPTION
**Pull request by shroff**

### CODE REVIEW

**Comment by rknell** [comment]
This looks really good. I've got to pull it down and have a play with it before I will merge it in, but it looks like a good solution from the quick skim I've had over it just now. Thanks!

**Comment by shroff** [comment]
Sure, no worries! Thanks for the great package.

**Comment by NathanDraco22** [comment]
This looks great... waiting

**Comment by rknell** [comment]
Thanks! I pulled it down locally and merged it in as there has been a few changes since the PR that conflicted. So closing it here but its about to come out in the new v1 Alfred release. Awesome work and sorry it took so long to merge it in.

**Pull request closed without merging**
